DKK = float(input("Hello user, how many DKK du you want to convert?\n"))

EUR = (DKK * 7.46)
USD = (DKK * 6.79)
AUD = (DKK * 4.5)
GBP = (DKK * 8.31)
SEK = (DKK * 0.71)
NOK = (DKK * 0.69)

print ("EUR " + str(EUR))
print ("USD " + str(USD))
print ("AUD " + str(AUD))
print ("GBP " + str(GBP))
print ("SEK " + str(SEK))
print ("NOK " + str(NOK))
